[tool.poetry]
name = "arcplot"
version = "0.1.2"
description = "arcplot is a library based on matplotlib for seamless creation of arc diagrams."
authors = ["Csaba Szallós Kis"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
contourpy = "1.2.0"
cycler = "0.12.1"
fonttools = "4.48.1"
kiwisolver = "1.4.5"
matplotlib = "3.8.2"
numpy = "1.26.4"
packaging = "23.2"
pillow = "10.2.0"
pyparsing = "3.1.1"
python-dateutil = "2.8.2"
six = "1.16.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
